### ISSUE TITLE
[Dev] Implement searchbar

### ISSUE THREAD

**Issue by discombobulateme** [saucelabs/elemental-next#10]
Implement a searchbar component in elemental-bromine

- [ ]  Add a searchbar component in the Menu to be accessible across all the pages

**Comment by aquaomarine** [comment]
We could use [Agolia](https://docusaurus.io/docs/search#using-algolia-docsearch) but it requires redeploying the site and going through their application process. Unless you'd like a search option. The component would mean us having to build our own search algorithm.

**Comment by discombobulateme** [comment]
@aquaomarine we use Algolia, it is a great option :) go for it! They should have a free version

**Comment by diemol** [comment]
I believe this is already present. Closing.
