### ISSUE TITLE
Community strategy to Fellowship

### ISSUE THREAD

**Issue by discombobulateme** [saucelabs/elemental-next#102]

**Comment by janackeh** [comment]
- met with Rachel on Tuesday to discuss ideas and options
- met with fellows on Wednesday to further discuss ideas and come up with a plan
- creating a Notion page to help organize and schedule weekly blog posts about fellowship

**Comment by discombobulateme** [comment]
Dear @janackeh, in order to improve transparency, could you please share document links so others can follow? Maybe also screen shots?

**Comment by janackeh** [comment]
![Image](https://user-images.githubusercontent.com/50855671/226377465-ca048ac2-74ff-49af-a2df-2e6dadf6aa5e.png)

**Comment by discombobulateme** [comment]
Hi @janackeh I cannot find the document in Notion o_O could you please provide a link to we can review and close this issue? Thank you :)

**Comment by janackeh** [comment]
https://www.notion.so/janackeh/Sauce-Labs-Fellowship-Community-Strategy-8ecf62ae7cf848589034d08a0289afbe?pvs=4

**Comment by discombobulateme** [comment]
Now I can access it :)

**Comment by janackeh** [comment]
meeting w Django tomorrow, meeting w Esther Friday to interview them to create content about the fellowship

**Comment by janackeh** [comment]
Currently working on Design w Django : https://docs.google.com/document/d/1H-wi_mgBnJptbfGtBm9g4KfWSbmJGv_hkXQ5gKAs2dI/edit?usp=sharing

**Comment by janackeh** [comment]
created a new and improved Notion as part of the Sauce Labs fellowship Notion here : https://www.notion.so/4c6867a66ab94e24bcb29bb6bd119ff9?v=90739e59434c47d6837f1cb353db3ea8
