### ISSUE TITLE
Create a new tip for Elemental Selenium

### ISSUE THREAD

**Issue by discombobulateme** [saucelabs/elemental-next#11]
A former Sauce Labs created a new tip that was never published!
The tip can be found here: Tip [73 Open a New Window or Tab – Selenium 4](https://docs.google.com/document/d/1akzOd2ysnsA2H1CMFJVD4ky7ViNf359QrpWg3-SupUg/edit?usp=sharing)

- [x]  Create a new tip following the new tip template
- [x] Add it to Elemental-Next

**Comment by Roseywinter** [comment]
New tip added to updated tips!
