### ISSUE TITLE
Validate Java beginner tips

### ISSUE THREAD

**Issue by discombobulateme** [saucelabs/elemental-next#110]
Validate code snippets, and update copy content.

Remember to:

- [x] Create a new folder under updated-content (example: `0-template`)
- [x] Inside of the folder, a markdown file named as the programing language validated should be created. (example: `python.md`)
- [x] In the case you cannot validate/run the code snippet, add a tag, something like: `Code needs validation`
- [x] Delete the equivalent tip folder under `non-updated-tips` folder

Tips Code Validation

- [x] Tip 1 
- [x] Tip 3
- [x] Tip 5
- [x] Tip 13
- [x] Tip 45
- [x] Tip 50
- [x] Tip 51
- [x] Tip 61
(8 tips total)

Tips Content Validation (and new category)

- [x] Tip 1 - remote, fundamentals
- [x] Tip 3 - fundamentals
- [x] Tip 5 - fundamentals
- [x] Tip 13 - troubleshooting
- [x] Tip 45 - fundamentals
- [x] Tip 50 - fundamentals
- [x] Tip 51 - fundamentals, tools
- [x] Tip 61 - fundamentals
(8 tips total)

**Comment by daniellemadry** [comment]
The folder has already been created correct, in the updated-tips folder?

**Comment by daniellemadry** [comment]
Yes I understand now thank you

**Comment by Roseywinter** [comment]
Done; closing Issue.
