### ISSUE TITLE
Elemental Selenium March update newslwtter

### ISSUE THREAD

**Issue by discombobulateme** [saucelabs/elemental-next#170]
Create a march update newsletter for Elemental Selenium users. 
It should contain the following: 

- [ ] a peak at a new tip #11 (talk with @Roseywinter to validate it)
- [ ] a reminder about SeleniumConf discount code
- [ ] Promote the team: meet the felloes in the Sauce Labs Community Blog

**Comment by janackeh** [comment]
in progress, will have done for editing by Tuesday 3/21 at latest

**Comment by janackeh** [comment]
newsletter is ready to be published, content link above

**Comment by discombobulateme** [comment]
Sent!
