### ISSUE TITLE
Add Vector to Dropdown Filters

### ISSUE THREAD

**Issue by aquaomarine** [saucelabs/elemental-next#313]
The Dropdown Filters on the **Tip Page** are missing the vector used in the Design and need to be added to help instruct use.

- [x] Add vector to Difficulty, Tag, and Category Dropdown

![Image](https://user-images.githubusercontent.com/45857126/227617164-26519d74-45a8-43e7-b34b-3b3885150c2f.png)
[Figma](https://www.figma.com/file/rgWBgdOEtXtlph6qTfAiEm/Wireframing?node-id=65-2&t=CT6wBtxQD7rh64PJ-0)

**Comment by discombobulateme** [comment]
@aquaomarine please add an image (in case people cannot access figma) to make it more understandable to people arriving now at the project, context, and acceptable criteria :)
