### ISSUE TITLE
[Dev][Tips] Create traffic light component

### ISSUE THREAD

**Issue by aquaomarine** [saucelabs/elemental-next#314]
Each tip card should show a traffic light system revealing if the tip is level 1, 2 or 3. 
This should be a component that fetches level information from the data.js file. 
The traffic light should be a if/ else statement showing a different svg representing each level or a div with the css

## Acceptance Criteria

- [x]  Each card needs to display a difficulty rating level expressing level 1, 2 or 3 showed as traffic lights
- [x] For [accessibility](https://css-tricks.com/accessible-svgs/), please apply either title or img with alt

**Comment by discombobulateme** [comment]
@aquaomarine could you describe this issue better? Without context, its really hard to understand what you mean. 
Try to describe where it needs to be implemented, which component are you talking about, where it needs to be displayed, which characteristics it needs to follow... etc. 
Add design images and acceptance criteria.

**Comment by daniellemadry** [comment]
Is this already done in one of the tips? Is this a picture we placing or a graphic. Is this a automation of some sort. Can I get a little more information?

**Comment by aquaomarine** [comment]
> Is this already done in one of the tips? Is this a picture we placing or a graphic. Is this a automation of some sort. Can I get a little more information? @aquaomarine

No it would be styled as a reusable component using css, and react.  You may need to use uneditable Radios, but Django has styled them using just CSS. It would be applied depending on the difficulty in the data object.
