### ISSUE TITLE
Update design components: Dropdown menu

### ISSUE THREAD

**Issue by Globnartheexquisite** [saucelabs/elemental-next#349]
# Description

The dropdown menu needs to be updated so that the different instances actually have different options in them! Django to do this today, Mar 29, as part of #229

# Criteria 

- [ ] Sort By (Date - New to Old, Date - Old to New, Difficulty - Lowest First, Difficulty - Highest First)
- [ ] Filter By (Categories) 
- [x] Language (C#, Java, JavaScript, Python, Ruby)

**Comment by diemol** [comment]
We are now using the Dropdown provided by Infima, the CSS toolkit embedded in Docusaurus.
