### ISSUE TITLE
[Dev] Implement Design System

### ISSUE THREAD

**Issue by aquaomarine** [saucelabs/elemental-next#366]
Description: Implement the Design system that's in Figma in the CSS of the project. 

## Acceptance criteria

- [ ] Create a `variables` folder to separate design variables ex: `frontend/src/css/variables/colors.modules.css`
- [x] Define root variables at `frontend/src/css/custom.css` file with either default ifm styles or override it
- [ ] Use only variables for repeatable values

**Comment by discombobulateme** [comment]
Started a branch design-system

**Comment by discombobulateme** [comment]
Closing the issue as system was implemented overriding Docusaurus default ifm color system
