### ISSUE TITLE
[Doc]Update README.md

### ISSUE THREAD

**Issue by discombobulateme** [saucelabs/elemental-next#377]
# Description
This project was forked from a template and needs its best practices files (readme.md codeofconduct.md, etc etc ) filled out. [Here](https://opensource.saucelabs.com/check-my-repo/rules) you can find a small description of what should contain in each of the best practices files.

## Acceptance Criteria

- [x] Update the [README.md](https://github.com/saucelabs/elemental-next/blob/main/README.md) file in the root (not the one inside of /frontend) explaining about what is Elemental Selenium

**Comment by Roseywinter** [comment]
Updated README.md
