### ISSUE TITLE
[Dev] Create resources page

### ISSUE THREAD

**Issue by discombobulateme** [saucelabs/elemental-next#378]
(See PR #439)

Create the resources page that reflects the design. Consider it as a wireframe with placeholders, do not get attached to styles.

Iteration 1:

- [x] Themes from current iteration will be added (footer/navbar)
- [x] Text from Figma will be added 
- [x] Links Will be added using Flexbox
1. Images also need to be added

Iteration 2:

- [ ] Navbar will be reflected as in the design
- [ ] Menu will be reflected as in the design
- [ ] Styling will better reflect Figma Design 

Acceptance Criteria:
Scope is overlapping with #434 which should go first
Deploy so this page is accessible at /resources

![Image](https://user-images.githubusercontent.com/7980624/232541747-1b706608-37ba-4cb4-9e67-e8955a306a6e.png)

**Comment by discombobulateme** [comment]
@aquaomarine if this issue is ready to be reviewed, can you please add the PR link here?

**Comment by aquaomarine** [comment]
> @aquaomarine if this issue is ready to be reviewed, can you please add the PR link here?

It's linked under development but here's also a[ link.](https://github.com/saucelabs/elemental-next/pull/439)

**Comment by discombobulateme** [comment]
@aquaomarine requested 2 small changes :) 
For the image, instead of 2 values, just give css 1 value: hight or width. That should fix the distortion :)

**Comment by Roseywinter** [comment]
Added reference to PR #439 in Issue description for easy access/visibility.
