### ISSUE TITLE
[Dev] Create footer

### ISSUE THREAD

**Issue by discombobulateme** [saucelabs/elemental-next#380]
(See PR #438)

Create footer, independent on the overlay image
You can create the footer in the docusaurus.config.js file
To configure the footer check: https://docusaurus.io/docs/api/themes/configuration#footer-1 

## Acceptance criteria

- [x] Footer appears on all the pages
- [ ] It needs to reflect the following design

![Image](https://user-images.githubusercontent.com/7980624/229571687-8d447da7-09a2-4a14-a757-3fdc57f4db3b.png)

**Comment by aquaomarine** [comment]
Needs to add additional routing for Tips Archive Links to be Viable

**Comment by aquaomarine** [comment]
- [x] added footer background image
- [x] changed content in footer to css in Sigma

Nice to Have:
- [ ] external links have underline
- [ ] Individual Routes for Beginner, Intermediate, and Advanced Tips for the Footer links

**Comment by aquaomarine** [comment]
![](https://user-images.githubusercontent.com/45857126/231905762-05ef797b-ec64-4dc4-b214-4de6bb7d65c8.png)

**Comment by discombobulateme** [comment]
@Globnartheexquisite please check the deployed: https://opensource.saucelabs.com/elemental-next/tips/ to see if design need adjustments for different screen sizes :)

**Comment by Globnartheexquisite** [comment]
@discombobulateme I'll review this today before our team meeting at 12 est. I have also added an issue covering a broader review to be undertaken this week and added you and @aquaomarine as additional assignees.

**Comment by Globnartheexquisite** [comment]
To add to this: 

The content of the footer is currently incorrect, but that needs to be addressed with content as well to see what the best practices would be for including links in the tips archive. 

The typesetting and spacing also need to be updated. 

The specific copy needs to be updated to match our current footer.

**Comment by claramyko** [comment]
Moving this to the Week column, to adjust priorities. Please finish the other #434  and #382  issues first.

**Comment by Roseywinter** [comment]
Added reference to PR #438 in Issue description for easy access.

**Comment by Roseywinter** [comment]
Will there be placeholder links added to the Tips Archive column (for Beginner Tips, Fundamentals, Troubleshooting), or is there a consensus to keep that column as "All Tips" for now? Other than this confusion, the footer looks good, and all links appear to be working fine.
