### ISSUE TITLE
[Dev] Implement header (menu)

### ISSUE THREAD

**Issue by discombobulateme** [saucelabs/elemental-next#382]
Implement the menu across all the pages per design.
To configure Docusaurus menu check: https://docusaurus.io/docs/api/themes/configuration#navbar

- [X] Logo in text - changing to logo image will be later in #383 
- [x] link to Tips
- [x] link to Community
- [x] link to Resources
- [x] link to Join - proposed to have Join button for every page, so there should be no difference for Home page
- [x] Make sure there are no other links (remove Sign In and dark mode)

![Image](https://user-images.githubusercontent.com/7980624/229574086-de233707-560a-4714-badd-2b957c9733a6.png)

**Comment by aquaomarine** [comment]
Do we have a link for a mailing list?

**Comment by discombobulateme** [comment]
@aquaomarine not yet :/ you can leave the Join the mailing list button without a link. @Globnartheexquisite will work on a design for either an input or a page.

**Comment by Roseywinter** [comment]
Logo looks great!

Small note about community link:

-  Link to "Community" says "Contribute"
-  Contribute link is "Page not found"

**Comment by discombobulateme** [comment]
Wireframes have been changed, this PR address that too 

![Image](https://user-images.githubusercontent.com/7980624/235724750-419c20d1-d662-4afd-838b-15e1db0edc96.png)
