### ISSUE TITLE
[Dev] Elemental Selenium Header Name

### ISSUE THREAD

**Issue by discombobulateme** [saucelabs/elemental-next#383]
- [x] Change the Header to fit the Figma Design for the Site Name (Specifically the text size, and Color)

Need logo image from @Globnartheexquisite 

[Figma](https://www.figma.com/file/rgWBgdOEtXtlph6qTfAiEm/Wireframing?node-id=132-34&t=CT6wBtxQD7rh64PJ-0)

**Comment by discombobulateme** [comment]
This is related to #382 
Question: isn't better to have the logo as an image? The logo image is added to the docusaurus.config file

**Comment by Roseywinter** [comment]
Looks like PR #454 will fix this. Looks good!
