### ISSUE TITLE
[Com]Blog Post: Figuring it Out: Esther's Strategy for Learning on the Fly

### ISSUE THREAD

**Issue by janackeh** [saucelabs/elemental-next#387]
This is part of a communication plan that can be followed in [Notion](https://www.notion.so/4c6867a66ab94e24bcb29bb6bd119ff9?v=90739e59434c47d6837f1cb353db3ea8
) 

- [x] Interview Esther
- [x] Write blog post - [Figuring it Out: Esther's Strategy for Learning on the Fly](https://docs.google.com/document/d/16hP17WtAeQxyQ1dH-75UY0CtIG2RFaPbe0m8z6jSa-w/edit?usp=sharing)
- [x] Send it to Rachel for review and publishing
- [x] Published!

**Comment by discombobulateme** [comment]
Blog has been published [here](https://saucelabs.com/resources/blog/figuring-it-out-esthers-strategy-for-learning-on-the-fly)! https://saucelabs.com/resources/blog/figuring-it-out-esthers-strategy-for-learning-on-the-fly
