### ISSUE TITLE
Validate Advanced Tips (BrowserMob Proxy) 

### ISSUE THREAD

**Issue by Roseywinter** [saucelabs/elemental-next#422]
- Escalating to @diemol for: Unable to validate code / unable to use BrowserMob Proxy
- Tips can be found in **updated folder** (accidentally merged Draft PR) 

Needs to be done:
- [ ] Code validated/fixed by expert, as necessary
- [ ] Edit instructions as necessary after code is validated 

Tips : 

- [ ]  Tip 17 ([link](https://github.com/saucelabs/elemental-next/blob/main/frontend/docs/updated-tips/17-retrieve-http-status-codes/17-retrieve-http-status-codes.md)) 
- [ ]  Tip 48 ([link](https://github.com/saucelabs/elemental-next/blob/main/frontend/docs/updated-tips/48-load-testing/48-load-testing-ruby.md)) 
- [ ]  Tip 49 ([link](https://github.com/saucelabs/elemental-next/blob/main/frontend/docs/updated-tips/49-performance-testing/49-performance-testing-ruby.md)) 
- [ ]  Tip 64 ([link](https://github.com/saucelabs/elemental-next/blob/main/frontend/docs/updated-tips/64-limit-bandwidth/64-limit-bandwidth-ruby.md)) 
- [ ]  Tip 66 ([link](https://github.com/saucelabs/elemental-next/blob/main/frontend/docs/updated-tips/66-blacklist/66-blacklist-ruby.md)) 
- [ ]  Tip 67 ([link](https://github.com/saucelabs/elemental-next/blob/main/frontend/docs/updated-tips/67-broken-images/67-broken-images-ruby.md)) 
- [ ]  Tip 68 ([link](https://github.com/saucelabs/elemental-next/blob/main/frontend/docs/updated-tips/68-load-testing-revisited/68-load-testing-revisited-ruby.md))
(7 tips total)

**Comment by diemol** [comment]
I see these tips were already reviewed and merged.
