### ISSUE TITLE
Review current deployment 4/17/2023

### ISSUE THREAD

**Issue by Globnartheexquisite** [saucelabs/elemental-next#432]
# Description 

Django to review alpha deployment of the site as of 4/17/2023 per Paloma's request. Critique and notes to be posted in the comments here below. 

# Criteria 

The following pages reviewed 

- [ ] Landing Page
- [ ] Tips list
- [ ] Individual tip
- [ ] Contribute
- [ ] External Resources

**Comment by discombobulateme** [comment]
Deployed website: https://opensource.saucelabs.com/elemental-next/
