### ISSUE TITLE
[Com][Event]Twitter Space: the fellows

### ISSUE THREAD

**Issue by janackeh** [saucelabs/elemental-next#433]
Host a Twitter audio space event to help promote ES

## Description 
A Twitter Space featuring the fellows to talk about the ES project as open source and the process that went into taking the tips from a newsletter to an OSP.
Having a **Call to Action** : signing up for Elemental Selenium to find out when they can start contributing to the project

If needed, PyLadies Berlin offers a very comprehensive guideline for organizing an event. Use it to create your own checklist for helping setup all the steps and offer transparency to your colleagues: http://berlin.pyladies.com/community-organisation/sub_pages/facilitating_events.html

## Checklist

- [ ] Date - TBD April 24-28
- [ ] Participants: TBD
- [ ] Questions for participants to answer
- [ ] Promote the event **time to promote the event (at least 3 -5 days) online to ensure a live audience**
-- [ ] Twitter promotion
-- [ ] Repost from SauceLabs (check with Rachel)

**Comment by discombobulateme** [comment]
Recording: https://twitter.com/i/spaces/1eaJbrOoPaoJX?s=20
