### ISSUE TITLE
[Dev] Individual Tip Page - left sidebar

### ISSUE THREAD

**Issue by discombobulateme** [saucelabs/elemental-next#437]
This is the first iteration of creating the page, which follows the design in the image below. 
Please consider the most basic structure, such as a wireframe, without losing time with styling.
But consider that this page will contain:

- [ ] codeblocks
- [ ] image

![Image](https://user-images.githubusercontent.com/7980624/232542559-da4cff9d-bc0c-455d-aa44-e6906d0d311d.png)

**Comment by discombobulateme** [comment]
Currently we are displaying all the pages in the sidebar. 
I tried adding hide_sidebar: true in the languages -md files but it didn't work o_O
In my opinion, ideally, for a first iteractions, the sidebar should display all the main.mdx files (new architecture), but not the languages

**Comment by diemol** [comment]
I enabled the sidebar, but it squeezes the content. I'll leave it as it is and if there is a nicer way to do it, we'll recheck.
