### ISSUE TITLE
[Dev][Tips]Add category tag

### ISSUE THREAD

**Issue by discombobulateme** [saucelabs/elemental-next#444]
Tips page contains individual tip cards.
The cards have tags.
This issue should add all the tags, which will **later** #447 serve as filters.
Some tags have special colors. 
Check with @Globnartheexquisite the final tags colors

![Image](https://user-images.githubusercontent.com/7980624/233713813-4fdd992f-30e5-455e-8a36-37c83a007690.png)

Tags are defined in the docs metadata

![Image](https://user-images.githubusercontent.com/7980624/233701327-e07ca269-bb0c-4518-8ede-1e6d736ea692.png)

**Comment by diemol** [comment]
Category tags were added.
