### ISSUE TITLE
[Doc]Update CONTRIBUTING.md

### ISSUE THREAD

**Issue by discombobulateme** [saucelabs/elemental-next#449]
# Description
This project was forked from a template and needs its best practices files (readme.md codeofconduct.md, etc etc ) filled out. [Here](https://opensource.saucelabs.com/check-my-repo/rules) you can find a small description of what should contain in each of the best practices files.

Update the [CONTRIBUTING.md](https://github.com/saucelabs/elemental-next/blob/main/CONTRIBUTING.md) file in the root

## Acceptance Criteria

- [x] It should contain ways in which the community can contribute to the project (use PenPot demo as an inspiration)
- - [x] Contributing with content/ new tips
- - [x] Contributing with code 
- - [x] Contributing to testing
- - [x] Reporting bugs

**Comment by Roseywinter** [comment]
Updated CONTRIBUTING.md (PR #455)
