### ISSUE TITLE
[QA]Checking for broken links - study

### ISSUE THREAD

**Issue by discombobulateme** [saucelabs/elemental-next#450]
Let's focus on studying specific quality assurance flows using Cypress to test our website :)
Broken links will be one of the flows we will need to implement. 
To get started with a framework, please check Cypress and this [tutorial](https://www.lambdatest.com/blog/find-broken-links-using-cypress/)

Lets see how it goes... Docusaurus itself uses Jest and [custom stuff for E2E](https://github.com/facebook/docusaurus/blob/main/.github/workflows/tests-e2e.yml)

**Comment by Roseywinter** [comment]
Update: still studying Cypress basics.

**Comment by discombobulateme** [comment]
@Roseywinter I'll consider the study part as done, as now you are heading towards implementation ;)
