### ISSUE TITLE
[Com]Blog Post: From Dreams to Reality: The Challenges of Designing for Functionality

### ISSUE THREAD

**Issue by discombobulateme** [saucelabs/elemental-next#451]
This is part of a communication plan that can be followed in [Notion](https://www.notion.so/4c6867a66ab94e24bcb29bb6bd119ff9?v=90739e59434c47d6837f1cb353db3ea8
) 

- [x] Interview Django 
- [x] Write blog post [From Dreams to Reality: The Challenges of Designing for Functionality](https://docs.google.com/document/d/1H-wi_mgBnJptbfGtBm9g4KfWSbmJGv_hkXQ5gKAs2dI/edit?usp=sharing)
- [x] Send it to Rachel for review and publishing
- [x] Published!

**Comment by janackeh** [comment]
Published : https://saucelabs.com/resources/blog/from-dreams-to-reality-the-challenges-of-designing-for-functionality
