### ISSUE TITLE
[Dev][Footer]Fix footer links to unrouted pages

### ISSUE THREAD

**Issue by discombobulateme** [saucelabs/elemental-next#456]
Beginner, Intermediate, and Advanced Tips are products of a filter applied to the content; there are no pages or routes that could take the user directly to those pages. 
But, the current footer design contemplates those links. 
Can you create links that take the users directly to each of those selections? Beginner, Intermediate, and Advanced Tips to fix the current footer links?

This issue aims to solve this issue either finding a solution to enable routering the links to a tips page displaying cards with only the selected tips level or proposing a new design compatible with the dev possibilities.

**Comment by diemol** [comment]
This was implemented.
