### ISSUE TITLE
[Doc]Add IssueTemplate

### ISSUE THREAD

**Issue by discombobulateme** [saucelabs/elemental-next#460]
Create IssueTemplates to allow users to add issues to our repository quickly and easier. 

You can follow these [instructions from GitHub](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository) as a reference, but add guidance adding acceptance criteria or something that matches these project expectations.

**Comment by Roseywinter** [comment]
Finished first draft. PR #483
