### ISSUE TITLE
[Com]Elemental Selenium April update newsletter

### ISSUE THREAD

**Issue by discombobulateme** [saucelabs/elemental-next#463]
Create a short update with relevant informations about the project revamp, maybe the new blog posts? and adding a launch date :)

**Comment by janackeh** [comment]
- [ ] working on this currently

**Comment by janackeh** [comment]
Here is the link : https://docs.google.com/document/d/1gRQ6JI77Oj2-Npp-m4EJeN5R9_maSZ0dzrvnPAb2twM/edit?usp=sharing

**Comment by Roseywinter** [comment]
Is this Issue completed? @janackeh @discombobulateme

**Comment by discombobulateme** [comment]
Sent!
