### ISSUE TITLE
[Dev][Tips] Frontmatter for Cards

### ISSUE THREAD

**Issue by aquaomarine** [saucelabs/elemental-next#464]
- [ ] Frontmatter Headline/Title needs to be changed
- [ ] Summary needs to be added to Frontmatter
- [ ] Add content url

**Comment by spider-sauce** [comment]
@aquaomarine do you already have a plan to create the `contenturl`? Leverage the `/slug` field perhaps?

**Comment by aquaomarine** [comment]
This issue has been broken down into minor issues.

**Comment by aquaomarine** [comment]
#issue 476
