### ISSUE TITLE
[Con][Tips]Frontmatter for Cards Ruby

### ISSUE THREAD

**Issue by aquaomarine** [saucelabs/elemental-next#466]
We'll need to change the front matter to include the following title, sidebar_label, and text to be readable for the cards on the tips page. This will give the routes for each tip, and make contributions more seamless. 

Acceptance Criteria:

- [x] Tip 1 - 16

- [x] Tip 17 - 32

- [x] Tip 33 - 48

- [x] Tip 59 - 72

```
---
title:' 0: Template'
id: '0-template-ruby'
sidebar_label: Ruby 
text: "This is a template."
number: 0
publish_date: 2023-02-17
last_update:
  date: 2023-02-24
tags:
  - 'template'
level: 0
category: 'template'
language: ruby
---
```
route `tips/template/0-template-ruby`

**Comment by discombobulateme** [comment]
@aquaomarine is this just for Ruby or ALL the tips? @Roseywinter this became a high importance, could you please take this?

**Comment by Roseywinter** [comment]
Just want to double check before I make changes, but is the title format really like this:

```
title: 0: Template'
```

**Comment by aquaomarine** [comment]
> @aquaomarine is this just for Ruby or ALL the tips? @Roseywinter this became a high importance, could you please take this?

Ruby is high priority since it's what we use for the tips page, I'm working making the issues for the other languages but I know this week is almost over.

**Comment by janackeh** [comment]
Completed updating frontmatter for all Ruby tips

**Comment by aquaomarine** [comment]
@janackeh thanks!

**Comment by Roseywinter** [comment]
Changed label to done, as all criteria are met.
