### ISSUE TITLE
[Con][Tips]Change Metadata for tips: CSharp

### ISSUE THREAD

**Issue by aquaomarine** [saucelabs/elemental-next#473]
We'll need to change the metadata in the tips files to include the following: title, sidebar_label, and text. This will make it readable for the cards on the tips page, and will give the routes for each tip, and make contributions more seamless. 

Acceptance Criteria:

- [x] Tip 1 - 16

- [x] Tip 17 - 32

- [x] Tip 33 - 48

- [x] Tip 59 - 72

```
---
title: '0: Template'
id: '0-template-csharp'
contentUrl: "/docs/updated-tips/0-template/c-sharp"
sidebar_label: CSharp
text: "This is a template."
number: 0
publish_date: 2023-02-17
last_update:
  date: 2023-02-24
tags:
  - 'template'
level: 0
category: 'template'
language: csharp
---
```

route `tips/template/0-template-csharp`

**Comment by Roseywinter** [comment]
@aquaomarine I see in the template example here, there is a slug, but in the updated ruby files, there is no slug. I want to clarify, when updating the csharp files, am I still adding slug? Or was slug removed? Thanks!

**Comment by Roseywinter** [comment]
Updated the metadata for the CSharp tips to match the metadata in the Ruby tips. (PR #239)

Example below (let me know if I understood the scope @aquaomarine):

```
---
title: '1: How To Upload A File'
id: '1-upload-a-file-csharp'
contentUrl: "docs/updated-tips/how-to-upload-a-file/1-upload-a-file-csharp"
sidebar_label: Csharp
text: "Uploading a file is a common piece of functionality found on the web but when trying to automate it, you get prompted with a dialog box that is just out of reach for Selenium. In these cases people often look to a third-party tool to manipulate this window."
number: 1
publish_date: 2019-08-09
last_update:
  date: 2023-03-28
tags:
  - 'file'
  - 'upload'
  - 'file upload'
level: 1
category:
  - remote
  - fundamentals
language: csharp
---

```

**Comment by Roseywinter** [comment]
Merged & done.
