### ISSUE TITLE
[Con][Tips]Change Metadata for tips: Javascript

### ISSUE THREAD

**Issue by aquaomarine** [saucelabs/elemental-next#477]
We'll need to change the metadata in the tips files to include the following: title, sidebar_label, and text. This will make it readable for the cards on the tips page, and will give the routes for each tip, and make contributions more seamless. 

Acceptance Criteria:

- [x] Tip 1 - 16

- [x] Tip 17 - 32

- [x] Tip 33 - 48

- [x] Tip 59 - 72

```
---
title: '0: Template'
id: '0-template-javascript'
contentUrl: "docs/template/0-template-javascript"
sidebar_label: Javascript
text: "This is a template."
number: 0
hide_table_of_contents: true
publish_date: 2023-02-17
last_update:
  date: 2023-02-24
tags:
  - 'template'
level: 0
category: 'template'
language: javascript
---
```
route `tips/template/0-template-javascript`

**Comment by Roseywinter** [comment]
Updated; PR #501

**Comment by Roseywinter** [comment]
Closed PR; will re-do.

**Comment by aquaomarine** [comment]
adding `hide_table_of_contents: true`

**Comment by Roseywinter** [comment]
Updated metadata, PR #521
