### ISSUE TITLE
[Dev]Add styles to Resources page

### ISSUE THREAD

**Issue by discombobulateme** [saucelabs/elemental-next#494]
/resources page is missing some styling

- [ ] Add the background image
- [ ] Fix distorted Icons
- [ ] Add arrow right icon after headers
- [ ] Use proper html tags for accessibility purposes ([check MDN](https://developer.mozilla.org/en-US/docs/Learn/Accessibility/HTML) as reference)

[Figma](https://www.figma.com/file/rgWBgdOEtXtlph6qTfAiEm/Wireframing?node-id=65-2&t=LjqHPxnOrUcbfWWs-0)

Notes:
- Footer color is out of the scope of this issue.

Styles should reflect the prototype, as in figma or the screenshot below:

![Image](https://user-images.githubusercontent.com/7980624/235720134-a3b3eb65-9cfb-4843-a172-c018efa56912.png)

**Comment by aquaomarine** [comment]
@discombobulateme what do you mean the icons are deformed?

**Comment by daniellemadry** [comment]
Is this issue about both of the pages: resources.js and resources.module.css?

**Comment by aquaomarine** [comment]
@daniellemadry Both, you'd have to style the elements in resources.js in the .css file.

The horizontal scroll wouldn't be a resource page issue though...so I wouldn't worry about that it's out of scope.

But I've asked @Globnartheexquisite to go over the current resource page, and critique the changes that need to be made in this issue for you for the last iteration.

**Comment by daniellemadry** [comment]
It does thank you.

**Comment by discombobulateme** [comment]
Hey @daniellemadry icons are distorted, take a look:

![Screenshot 2023-05-03 at 12 51 13 PM](https://user-images.githubusercontent.com/7980624/235896477-dde03e14-44af-4dd3-971c-5eaf54469504.png)

**Comment by discombobulateme** [comment]
@daniellemadry I re-scoped the issue :)

**Comment by aquaomarine** [comment]
> Hey @daniellemadry icons are distorted, take a look in this screenshot:
> 
> ![Screenshot 2023-05-03 at 12 51 13 PM](https://user-images.githubusercontent.com/7980624/235896477-dde03e14-44af-4dd3-971c-5eaf54469504.png)
> 
> And I agree with @aquaomarine , responsiveness will slow down this issue, Ill add it into another issue :)

Just making sure we're on the same page. This is caused by Figma's PNG export feature not being the best quality, so Django advised us to use [Advanced Export](https://www.figma.com/community/plugin/782713260363070260/Advanced-SVG-Export) and change the SVGs to PNGs.

**Comment by Globnartheexquisite** [comment]
I'm not certain that that is caused by Figma, when I inspect each icon they display in a new tab undistorted.

**Comment by aquaomarine** [comment]
> I'm not certain that that is caused by Figma, when I inspect each icon they display in a new tab undistorted. 

On export?

**Comment by Globnartheexquisite** [comment]
> On export? 

No as in right clicking on the individual element and selecting "open in new tab" in the site itself. The image itself isn't distorted, the embed or div block is.

**Comment by Globnartheexquisite** [comment]
@aquaomarine 

I'm unsure as to the scope of the review but I'll put the majority of my thoughts down here: 

1. The icons are distorted, you're aware of that, I assume it will be fixed soon. If there's anything I can assist with there, ping me. 
2. The typeface is visibly different, looking in the CSS I can see that roboto is within the type families listed, not sure why I'm not seeing it here. 
3: "Examples from Hands-On..." is clunky, I can see that, but putting the whole name runs down into two lines and that really doesn't look great. Let's abbreviate it to "Examples from Hands-On... With Java"
4. The spacing between the link text and the descriptor text is too small. There should be 12pt between the top of the text element and the bottom of the link element. 
5. The icons sit to high compared to the link elements, with large sections of the icons (~1/10) sitting above the top of the link text. Will this be rectified when the icons are no longer stretched? 
6. There is still no rocketship in the footer. Do you need me to export you a transparent element for that whole footer section? 
7. Speaking of the footer, there's nearly a full screen of whitespace between it and the bottom element of the list. 
8. The logo at the top left on the nav bar is very distorted. 
9. When I hover over External Resources in the nav bar it bolds (good!) and then when I move away from it, it goes back to thin (also good!) and then flashes brown, white, and goes back to black in about a quarter second. Is this a docusaurus issue? It's very distracting. 
10. The main copy on the page has line breaks which orphan two words at the bottom despite there being more than enough space on my monitor to put it on less lines. I've also just now updated the copy on the figma after I found several typos in my own work, apologies for not catching that earlier!

**Comment by daniellemadry** [comment]
-- Working on the background image. Are these located on Figma @Globnartheexquisite ?

**Comment by aquaomarine** [comment]
I've linked the Figma, I've also fixed the added the Roboto font, and fixed the width distortion in the last PR.

**Comment by discombobulateme** [comment]
Hey @daniellemadry please check that there was a refactor in the code and all css files now are under css folder :)

**Comment by daniellemadry** [comment]
@discombobulateme Thank you. I was wondering what happened.

**Comment by discombobulateme** [comment]
Closed with PR #512
