### ISSUE TITLE
[Dev] Change data.js output from script to frontend/src

### ISSUE THREAD

**Issue by aquaomarine** [saucelabs/elemental-next#496]
frontend/src/scripts/**getFrontmatter.js**  is a script that gets all he metadata from docs .md files and creates a data.js file
The script runs everytime the build script runs and overrides the file
Output should is now in the script folder, but it should be in the src root folder **frontend/src**

**Comment by discombobulateme** [comment]
Fixed at #498 
https://github.com/saucelabs/elemental-next/pull/503

Source data stayed at the script folder
