### ISSUE TITLE
[Dev][Card]Fix tags spacing

### ISSUE THREAD

**Issue by discombobulateme** [saucelabs/elemental-next#504]
Each individual tip card displays tags as a single word. It needs to be displayed properly, with spacing.
Fox example, tip 23 has the following tags: 
tags:
  - 'dynamic pages'
  - 'ajax'
  - 'javascript'
  - 'waiting'
  - 'explicit waits'

This is how is displayed:

![Image](https://user-images.githubusercontent.com/7980624/236548226-a172ccfb-716f-4105-b61b-e1deef743247.png)

**Comment by aquaomarine** [comment]
those look like a lot of tags for buttons on a card, do you think they could be too much?
