### ISSUE TITLE
[QA]Implement or rate accessibility testing across the website

### ISSUE THREAD

**Issue by discombobulateme** [saucelabs/elemental-next#518]
Run accessibility testing across the website, considering vision impairment and keyboard navigation
Create an issue enumerating what needs to be fixed as accessibility bug

[Reference](https://www.w3.org/WAI/test-evaluate/)

Use [Deque Axe Chrome Dev Tools](https://chrome.google.com/webstore/detail/axe-devtools-web-accessib/lhdoppojpmngadmnindnejefpokejbdd) to create reports

**Comment by Roseywinter** [comment]
First test runs were done, and I was trying to find the best way to create and share reports. It is still a work in progress, but these are the generated .csv reports so far from running the chrome extension tool:

https://drive.google.com/drive/u/2/folders/1FO81jyNV0N9wfyZF9LiwvpS3eNlw82GG

**Comment by Roseywinter** [comment]
Updated deque-tests folder with readme and links to reports. PR #560
