### ISSUE TITLE
[QA] Add workflow status badge

### ISSUE THREAD

**Issue by discombobulateme** [saucelabs/elemental-next#546]
Add a workflow status badge to the repo.

https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/adding-a-workflow-status-badge

**Comment by discombobulateme** [comment]
https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/adding-a-workflow-status-badge
https://www.npmjs.com/package/@axe-core/react

**Comment by Roseywinter** [comment]
Is the test-build.yml file in .github/workflows a file we can use to create the badge? If so, it looks like I just need to add this code to the main readme file:

```
https://github.com/saucelabs/elemental-next/actions/workflows/test-build.yml/badge.svg
```

**Comment by discombobulateme** [comment]
@Roseywinter we need to create a workflow that considers the tests you are creating to say if they all passed.
Right now, the only one we got was the build test. We can add it to it for now while we add the other tests to the workflow :)
Please make the changes you propose so we can add the badge and see how it will look like <3

**Comment by Roseywinter** [comment]
Adding test badge status for cypress tests: PR #563
