### ISSUE TITLE
[Dev] [QA] Tip Routing 404 Error

### ISSUE THREAD

**Issue by Tacktician** [saucelabs/elemental-next#548]
## Describe the Issue
Clicking on tip thumbnails leads to 404 HTTP response errors, possible broken links.

## To Reproduce
1. Navigate to [https://opensource.saucelabs.com/elemental-next/tips/](https://opensource.saucelabs.com/elemental-next/tips/) or navigate to [https://opensource.saucelabs.com/elemental-next/](https://opensource.saucelabs.com/elemental-next/) and select the hyperlink [**Skip it, take me to the tips**](https://opensource.saucelabs.com/elemental-next/tips)
2. Select any tip thumbnail / card
3. Should see the following page: 
<img width="1296" alt="Screenshot 2023-05-16 at 7 01 56 AM" src="https://github.com/saucelabs/elemental-next/assets/45496368/05abd52f-cb4a-48af-a016-1a1bf3cd1f56">

## Expected Behavior

Should redirect to the appropriate tip page as if you were to click *Tips* in the header

## Actual Behavior

Page not found / Docusaurus routing issue

**Comment by spider-sauce** [comment]
It looks like there's also a trailing slash issue:

[https://opensource.saucelabs.com/elemental-next/tips/](https://opensource.saucelabs.com/elemental-next/tips/)

vs.

[https://opensource.saucelabs.com/elemental-next/tips](https://opensource.saucelabs.com/elemental-next/tips)

**Comment by diemol** [comment]
This has been fixed.
