### ISSUE TITLE
[Dev][QA] Breadcrumbs too small

### ISSUE THREAD

**Issue by Tacktician** [saucelabs/elemental-next#549]
## Describe the Issue

Breadcrumbs for tips pages are too small, difficult to read.

## Screenshots
<img width="624" alt="Screenshot 2023-05-16 at 7 44 18 AM" src="https://github.com/saucelabs/elemental-next/assets/45496368/4c28ecf0-fab2-4e40-b7a3-1c45f54100fe">

## Additional Notes

This is probably a CSS issue.

**Comment by discombobulateme** [comment]
Fixed!
