### ISSUE TITLE
[Dev][Tips]Clear filters

### ISSUE THREAD

**Issue by discombobulateme** [saucelabs/elemental-next#555]
The current filter on the /tips page does not inform the user which filter has been selected not allow the user to clear the filters. This is not ideal for the user experience. 

Acceptance criteria

- [x] User should be able to see which filters are selected
- [x] User should be able to clear the selected filter by clicking in the selected item again

**Comment by discombobulateme** [comment]
@Globnartheexquisite now using the page kind of missing that o_O

**Comment by Globnartheexquisite** [comment]
Could you elaborate? @discombobulateme

**Comment by discombobulateme** [comment]
Fixed with PR #564
