### ISSUE TITLE
Update beginner tips in JavaScript

### ISSUE THREAD

**Issue by discombobulateme** [saucelabs/elemental-next#6]
We are starting an epic task to update Elemental Selenium content. 
Tips should be validated, and its content reviewed to fit the new tips headers, consdering inclusive language. 
Code snipets also need to be validated. 

- [x] Create a new folder under updated-content named with the new tip number and title using kebab-case. You should follow the folder example: `0-template`
- [x] Inside of the folder, a markdown file named as the programing languaged validated should be created. Example: `python.md`
- [x] The file should follow the tips template
- [ ] Delete the equivalent folder under `non-updated-tips` folder
- [x] Add a review tag, such as: Last review Day Month Year
- [x] In the case you cannot validate/ run the code snippet, add a tag, something like: `Code needs validation`

Typs Code Validation

- [x] Tip 1 
- [x] Tip 2
- [x] Tip 3
- [x] Tip 4
- [x] Tip 5
- [x] Tip 13
- [x] Tip 45
- [x] Tip 50
- [x] Tip 51
- [x] Tip 61

Typs Content Validation

- [x] Tip 1 
- [x] Tip 2
- [x] Tip 3
- [x] Tip 4
- [x] Tip 5
- [x] Tip 13
- [x] Tip 45
- [x] Tip 50
- [x] Tip 51
- [x] Tip 61

**Comment by aquaomarine** [comment]
Javascript beginner tips have been **completed**.

**Comment by daniellemadry** [comment]
Looks good, Great Job everyone.
