### ISSUE TITLE
Validate Medium Ruby Tips 2-23

### ISSUE THREAD

**Issue by discombobulateme** [saucelabs/elemental-next#68]
We are starting an epic task to update Elemental Selenium content. 
Tips should be validated, and its content reviewed to fit the new tips headers, considering inclusive language. 
Code snippets also need to be validated. 

- [x] Create a new folder under updated-content named with the new tip number and title using kebab-case. You should follow the folder example: `0-template`
- [x] Inside of the folder, a markdown file named as the programing language validated should be created. Example: `python.md`
- [x] The file should follow the tips template
- [x] Delete the equivalent folder under `non-updated-tips` folder
- [x] Add a review tag, such as: Last review Day Month Year
- [x] In the case you cannot validate/ run the code snippet, add a tag, something like: `Code needs validation`

Tips Code Validation

- [x] Tip 2
- [x] Tip 4
- [x] Tip 7
- [x] Tip 8
- [x] Tip 10
- [x] Tip 11
- [x] Tip 12
- [x] Tip 16
- [x] Tip 19
- [x] Tip 23
(10 tips total)

Tips Content Validation

- [x] Tip 2
- [x] Tip 4
- [x] Tip 7
- [x] Tip 8
- [x] Tip 10
- [x] Tip 11
- [x] Tip 12
- [x] Tip 16
- [x] Tip 19
- [x] Tip 23
(10 tips total)

**Comment by Roseywinter** [comment]
All tips updated. Created issues for tips that need expert attention (Tips 2, 7, and 8) and escalated to Diego. Closing this issue.
