### ISSUE TITLE
Fix sidebar

### ISSUE THREAD

**Issue by discombobulateme** [saucelabs/elemental-next#72]
Users should see a comprehensive title on the sidebar, reflecting each tip's different languages.

Currently, it is not possible to know to which language it refers.

![Image](https://user-images.githubusercontent.com/7980624/222405832-48f1ec3b-09c6-40b5-a151-12d93f404254.png)

Another option is to add tabs instead of replicating the files, such as showed in [this example](https://www.selenium.dev/documentation/webdriver/elements/file_upload/)

![Image](https://user-images.githubusercontent.com/7980624/222407302-fed1a0f8-291f-4e54-838f-2600ce53e05c.png)

In this case, when the example is missing, a button/ call to action is added to allow users to easily contribute. 

- [ ] Fix markdow to display it correctly (check in documentation how)
- [ ] Update contributor guideline with this information

**Comment by aquaomarine** [comment]
So it is in the Metadata- Title that it's being pulled from.

But I also found the interchangeable code blocks for docusaurus:
https://docusaurus.io/docs/markdown-features/code-blocks

So just depends on which we'd like to do.

**Comment by aquaomarine** [comment]
![Image](https://user-images.githubusercontent.com/45857126/223286007-1e2345f1-296d-49f5-a530-57f6716ef1eb.png)

**Comment by discombobulateme** [comment]
@aquaomarine awesome work :) 
Please talk to @Globnartheexquisite if is there a design option for that. 
What worries me about code block is that its not just a code block, its the whole Example and Author that has to change. 
So I believe in our case, metadata will do :) 
Please communicate your colleagues about the changes they need to do, also @janackeh to update the template :) 
thank you!
