### ISSUE TITLE
Mac user to verify Tip69

### ISSUE THREAD

**Issue by Roseywinter** [saucelabs/elemental-next#79]
Need a Mac user to validate Ruby Tip69 "How To Use Safari" ([link](https://github.com/saucelabs/elemental-next/tree/main/frontend/docs/non-updated-tips/69-safari)). (Related to issue #60 "Validated Beginner Tips in Ruby")

- [x] Technical content validated
- [x] Copy content validated
- [x] New directory and markdown file uploaded to updated tips folder
- [x] Old directory and markdown file deleted from nonupdated tips folder

**Comment by discombobulateme** [comment]
@aquaomarine will check
