### ISSUE TITLE
Tip 35 Deprecated information 

### ISSUE THREAD

**Issue by Roseywinter** [saucelabs/elemental-next#85]
This tip contains resources and instructions that are deprecated

Broken links and images need replacing if/when newer resource is found, and page is updated

Escalating to @diemol

**Comment by diemol** [comment]
@discombobulateme I think we need to delete this tip because the referenced tool does not exist anymore. There are other tools we might feature but we should reach to the owners of the tool(s) and ask them to contribute a tip. However we can only do that when the site is ready.
